vich_uploader:
    db_driver: orm

    mappings:
        products_images:
            uri_prefix: '%app.path.products_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.products_images%'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
            namer: Vich\UploaderBundle\Naming\UniqidNamer
<<<<<<< HEAD

=======
>>>>>>> ab499dbafb630e0c7b878b39638e76236f01c151
        header_images:
            uri_prefix: '%app.path.header_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.header_images%'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        category_images:
            uri_prefix: '%app.path.category_images%'
            upload_destination: '%kernel.project_dir%/public/%app.path.category_images%'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
            namer: Vich\UploaderBundle\Naming\OrignameNamer
