vich_uploader:
    db_driver: orm

    mappings:
        products_images:
            uri_prefix: '%app.path.products_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.products_images%'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        header_images:
            uri_prefix: '%app.path.header_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.header_images%'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        category_images:
            uri_prefix: '%category_images%'
            upload_destination: '%kernel.project_dir%/public%category_images%'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
            namer: Vich\UploaderBundle\Naming\OrignameNamer
